//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rental
    {
        public int RentalID { get; set; }
        public int CustomerID { get; set; }
        public int CarID { get; set; }

        [Display(Name = " Date Rented")]
        public Nullable<System.DateTime> DateRented { get; set; }

        [Display(Name = " Date Returned")]
        public Nullable<System.DateTime> DateReturned { get; set; }

        // Indicates that the Car and Customer properties in the Rental class are intended to be overridden in derived/child classes.
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
